import { useEffect, useState } from 'react';
import axios from 'axios';
import { Scale, Search, Library, Activity, ArrowUpRight, Copy, Check, Sparkles, ShieldCheck, X, ChevronRight, Clock3 } from 'lucide-react';
import { Toaster, toast } from 'sonner';
import './App.css';

const API = process.env.REACT_APP_BACKEND_URL;
const categories = ['All','Constitution','BNS','BNSS','Consumer Protection','Motor Vehicles','Supreme Court Judgments'];
const prompts = ['Can an undertrial seek bail under BNSS Section 479?','What is the Basic Structure doctrine?','What does Article 21 protect?','What remedy does a consumer have for deficient service?'];

export default function App() {
  const [tab,setTab] = useState('qa'); const [query,setQuery] = useState(''); const [scope,setScope] = useState('All');
  const [result,setResult] = useState(null); const [loading,setLoading] = useState(false); const [library,setLibrary] = useState([]);
  const [search,setSearch] = useState(''); const [history,setHistory] = useState([]); const [analytics,setAnalytics] = useState(null); const [detail,setDetail] = useState(null); const [copied,setCopied] = useState(false);
  const get = (path, params={}) => axios.get(`${API}${path}`,{params});
  useEffect(()=>{ get('/api/statutes').then(r=>setLibrary(r.data.statutes)); get('/api/research/history').then(r=>setHistory(r.data.queries)); get('/api/analytics').then(r=>setAnalytics(r.data)); },[]);
  const run = async (text=query) => { if(!text.trim()) return toast.error('Enter a legal question first.'); setLoading(true); try { const r=await axios.post(`${API}/api/research/query`,{query:text,statute_filter:scope,use_hybrid_search:true}); setResult(r.data); setQuery(text); setHistory((await get('/api/research/history')).data.queries); toast.success('Answer grounded in indexed sources'); } catch { toast.error('The research engine could not respond.'); } finally { setLoading(false); } };
  const filterLibrary = (value, category=scope) => { setSearch(value); get('/api/statutes',{category,search:value}).then(r=>setLibrary(r.data.statutes)); };
  const open = (id) => get(`/api/statutes/${id}`).then(r=>setDetail(r.data)).catch(()=>toast.error('Source unavailable'));
  const copy = async (text) => { try { await navigator.clipboard.writeText(text); setCopied(true); toast.success('Copied'); setTimeout(()=>setCopied(false),1600); } catch { toast.error('Clipboard access was blocked. Select and copy the text manually.'); } };
  const nav = [{id:'qa',label:'Ask Nyaya',icon:Search},{id:'library',label:'Source library',icon:Library},{id:'dashboard',label:'Corpus health',icon:Activity}];
  return <div className="shell"><Toaster position="top-right" richColors/><header className="topbar"><div className="brand"><div className="mark"><Scale size={20}/></div><div><div className="brand-name">Nyaya<span>AI</span></div><div className="brand-sub">Indian law · source-first research</div></div></div><nav className="nav" data-testid="primary-navigation">{nav.map(({id,label,icon:Icon})=><button data-testid={`nav-${id}`} className={tab===id?'nav-active':''} onClick={()=>setTab(id)} key={id}><Icon size={16}/>{label}</button>)}</nav><div className="engine"><i/> Local SLM <b>4B</b></div></header>
    <main className="main">{tab==='qa'&&<QAPage {...{query,setQuery,scope,setScope,result,loading,run,prompts,history,open,copy,copied}}/>}{tab==='library'&&<LibraryPage {...{library,search,filterLibrary,scope,setScope,open}}/>}{tab==='dashboard'&&<Dashboard {...{analytics,history}}/>}</main>
    {detail&&<div className="overlay" data-testid="source-detail-modal"><section className="modal"><button className="icon-btn close" data-testid="close-source-modal" onClick={()=>setDetail(null)}><X size={18}/></button><div className="eyebrow">{detail.category} · {detail.section}</div><h2>{detail.title}</h2><p className="lead">{detail.summary}</p><div className="source-text">{detail.full_text}</div><div className="tags">{detail.tags.map(t=><span key={t}>{t}</span>)}</div><div className="modal-actions"><button className="secondary" data-testid="copy-source-button" onClick={()=>copy(detail.full_text)}>{copied?<Check size={15}/>:<Copy size={15}/>} Copy source</button><button className="primary" data-testid="query-source-button" onClick={()=>{setTab('qa');setQuery(`What is the legal significance of ${detail.title}?`);setDetail(null)}}>Ask about this source <ArrowUpRight size={15}/></button></div></section></div>}
  </div>;
}
function QAPage({query,setQuery,scope,setScope,result,loading,run,prompts,history,open,copy,copied}){return <><section className="intro"><div><div className="eyebrow">LEGAL RESEARCH / 01</div><h1>Ask a better<br/><em>legal question.</em></h1><p>Retrieve the provisions and precedents behind an answer — before you rely on it.</p></div><div className="intro-note"><ShieldCheck size={20}/><span><b>Source-first by design</b><br/>Every response is tied to indexed Indian legal sources.</span></div></section><div className="workspace"><aside className="query-panel"><label className="label">Your research question</label><textarea data-testid="legal-question-input" value={query} onChange={e=>setQuery(e.target.value)} placeholder="e.g. What are the provisions for undertrial bail under BNSS?"/><label className="label">Search across</label><select data-testid="legal-scope-select" value={scope} onChange={e=>setScope(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select><button className="primary run" data-testid="run-research-button" onClick={()=>run()} disabled={loading}>{loading?<><span className="spinner"/>Finding sources…</>:<><Sparkles size={17}/> Run grounded research <ArrowUpRight size={16}/></>}</button><div className="prompt-list"><div className="label">Try a prompt</div>{prompts.map((p,i)=><button data-testid={`suggested-question-${i}`} key={p} onClick={()=>run(p)}>{p}<ChevronRight size={14}/></button>)}</div>{history.length>0&&<div className="history"><div className="label"><Clock3 size={13}/> Recent research</div>{history.slice(0,3).map(h=><button data-testid={`history-query-${h.id}`} key={h.id} onClick={()=>run(h.query)}><span>{h.query}</span><small>{h.confidence}%</small></button>)}</div>}</aside><section className="answer-panel">{result?<Answer {...{result,open,copy,copied}}/>:<div className="empty"><div className="empty-icon"><Scale size={32}/></div><h2>Your cited answer will appear here</h2><p>Ask about a provision, a right, or a precedent. NyayaAI retrieves the closest sources and keeps them visible alongside its synthesis.</p><div className="empty-rule"><span>01</span>Ask a question <span>02</span>Review sources <span>03</span>Verify the law</div></div>}</section></div></>}
function Answer({result,open,copy,copied}){return <div className="answer" data-testid="research-answer"><div className="answer-head"><div><div className="eyebrow">GROUNDED SYNTHESIS</div><h2>Research brief</h2></div><div className="confidence" data-testid="confidence-score"><span/> {result.confidence_score}% confidence</div></div><div className="metrics">{[['Vector match',result.retrieval_metrics.faiss_vector_score],['BM25 relevance',result.retrieval_metrics.bm25_score],['Retrieval',`${result.retrieval_metrics.latency_ms} ms`],['Model',result.retrieval_metrics.slm_model]].map(([k,v])=><div key={k}><small>{k}</small><b>{v}</b></div>)}</div><div className="answer-copy">{result.answer.split('\n').map((line,i)=><p key={i}>{line.startsWith('**')?line.replaceAll('**',''):line}</p>)}</div><div className="citation-section"><div className="section-heading">Retrieved sources <span>{result.citations.length} citations</span></div>{result.citations.map((c,i)=><button data-testid={`citation-source-${c.id}`} className="citation" key={c.id} onClick={()=>open(c.id)}><span className="cite-number">[{i+1}]</span><span><b>{c.title}</b><small>{c.act} · {c.section}</small></span><strong>{Math.round(c.relevance_score*100)}%</strong></button>)}</div><div className="disclaimer" data-testid="legal-disclaimer">{result.disclaimer}</div><button className="copy-answer" data-testid="copy-answer-button" onClick={()=>copy(result.answer)}>{copied?<Check size={14}/>:<Copy size={14}/>} Copy answer</button></div>}
function LibraryPage({library,search,filterLibrary,scope,setScope,open}){return <><section className="page-head"><div><div className="eyebrow">SOURCE LIBRARY / 02</div><h1>Know what<br/><em>supports you.</em></h1><p>Browse the indexed statutes and judgments available to the local research engine.</p></div><div className="library-count"><b>{library.length}</b><span>available sources</span></div></section><div className="library-tools"><div className="searchbox"><Search size={17}/><input data-testid="library-search-input" value={search} onChange={e=>filterLibrary(e.target.value)} placeholder="Search sections, cases, rights…"/></div><select data-testid="library-category-select" value={scope} onChange={e=>{const category=e.target.value;setScope(category);filterLibrary(search,category)}}>{categories.map(c=><option key={c}>{c}</option>)}</select></div><div className="source-grid">{library.map(s=><button data-testid={`library-source-${s.id}`} className="source-card" key={s.id} onClick={()=>open(s.id)}><div className="card-top"><span>{s.category}</span><small>{s.section}</small></div><h3>{s.title}</h3><p>{s.summary}</p><div className="card-foot">Read source <ArrowUpRight size={15}/></div></button>)}</div></>}
function Dashboard({analytics,history}){if(!analytics)return <div className="empty"><span className="spinner"/></div>;return <><section className="page-head"><div><div className="eyebrow">CORPUS HEALTH / 03</div><h1>A clear view of<br/><em>your evidence.</em></h1><p>Understand the corpus and retrieval system behind every research brief.</p></div></section><div className="stat-grid">{[['Indexed documents',analytics.total_indexed_documents.toLocaleString(),'Corpus size'],['SC judgments',analytics.supreme_court_judgements.toLocaleString(),'Landmark & constitutional'],['Average retrieval',`${analytics.avg_retrieval_time_ms} ms`,'Hybrid ranking'],['Recent questions',history.length,'This session']].map(([a,b,c])=><div className="stat" data-testid={`stat-${a.replaceAll(' ','-').toLowerCase()}`} key={a}><small>{a}</small><b>{b}</b><span>{c}</span></div>)}</div><div className="dashboard-grid"><div className="chart"><div className="section-heading">Corpus by practice area</div>{analytics.category_breakdown.map(c=><div className="bar-row" key={c.category}><div><span>{c.category}</span><b>{c.count.toLocaleString()}</b></div><div className="bar"><i style={{width:`${Math.min(100,c.count/450)}%`}}/></div></div>)}</div><div className="architecture"><div className="section-heading">How NyayaAI stays grounded</div><div className="arch-item"><span>01</span><div><b>Retrieve</b><p>Keyword and semantic matching find relevant provisions.</p></div></div><div className="arch-item"><span>02</span><div><b>Constrain</b><p>Only retrieved sources enter the local answer context.</p></div></div><div className="arch-item"><span>03</span><div><b>Verify</b><p>Citations remain visible so you can check the source.</p></div></div></div></div></>}